language: ruby
rvm:
- 2.0.0-p647

bundler_args: --jobs=1
script:
 - bundle exec rake db:create
 - bundle exec rake db:migrate
 - bundle exec rake db:seed
 - bundle exec rake spec
cache: bundler
services:
 - postgresql
env:
  global:
    - secure: "HoNp0ribAHqCcd6+5nqZ+XFP/giVmJZxBu2qUHs9xjHeBSNr6wZRbT8IRTjQ031pKXvwy/mStVkDBs+DAnIffRBNXjCTK9CRpICsMJ2gBnu3KNOWur6X4wP6EC9QYs6k767lqPqHpkrK1HCKQIuObVK5m6HcqOWdtyFTpMQ5TstwAX+YW2GXW2mUDWIwaxaI1wmRCjxY3vxEhjwlLGlBE03tQWy4c+IsgaH4XPfwvjOQ3G3ACtfo76aQdDm/rKY3je/PWMGXAYnxL5D9w25Vy9yUVYQRE7677QKnQwhbrjtCyDHMhYxHn20JcTCOxcKE9enyzSAQtG/RRHK/DV6Cpl8j4Enwbord2tLJ9T+7QRN0Hhc3M4L61kMGgtpX3dkNfQCJc9uIbC+xLXrKBnaxXhvL9ybLBUy9fwAh21Ouy0fym2kN0+a8g+VElP/vc2RShB+tbcx9kDoyLPJewMcwh+spzPuw1hM0N0P1LgfQj7huJDJhKSlc7t0BLendzY0bA5+/9goucdoPXwUpX41UwrnCZ4yK/C89FCxd9U8Urh/gZsQJPKHaLpQTx8kwWL/R3HRcXOxBzIkwW7ATp+8ibwphdCktqAuLkf0THgmC6cetykCiQ6pb9cKBw+d6NEA+OeJBr/SZvaPENnizInVsyoLIF0cl7Ui9OH7Y7viLqaQ="
