language: ruby
rvm:
- 2.0.0-p647

bundler_args: --jobs=1
script:
 - bundle exec rake db:create
 - bundle exec rake db:migrate
 - bundle exec rake db:seed
 - bundle exec rake spec
cache: bundler
services:
 - postgresql
env:
  global:
    - secure: "HoNp0ribAHqCcd6+5nqZ+XFP/giVmJZxBu2qUHs9xjHeBSNr6wZRbT8IRTjQ031pKXvwy/mStVkDBs+DAnIffRBNXjCTK9CRpICsMJ2gBnu3KNOWur6X4wP6EC9QYs6k767lqPqHpkrK1HCKQIuObVK5m6HcqOWdtyFTpMQ5TstwAX+YW2GXW2mUDWIwaxaI1wmRCjxY3vxEhjwlLGlBE03tQWy4c+IsgaH4XPfwvjOQ3G3ACtfo76aQdDm/rKY3je/PWMGXAYnxL5D9w25Vy9yUVYQRE7677QKnQwhbrjtCyDHMhYxHn20JcTCOxcKE9enyzSAQtG/RRHK/DV6Cpl8j4Enwbord2tLJ9T+7QRN0Hhc3M4L61kMGgtpX3dkNfQCJc9uIbC+xLXrKBnaxXhvL9ybLBUy9fwAh21Ouy0fym2kN0+a8g+VElP/vc2RShB+tbcx9kDoyLPJewMcwh+spzPuw1hM0N0P1LgfQj7huJDJhKSlc7t0BLendzY0bA5+/9goucdoPXwUpX41UwrnCZ4yK/C89FCxd9U8Urh/gZsQJPKHaLpQTx8kwWL/R3HRcXOxBzIkwW7ATp+8ibwphdCktqAuLkf0THgmC6cetykCiQ6pb9cKBw+d6NEA+OeJBr/SZvaPENnizInVsyoLIF0cl7Ui9OH7Y7viLqaQ="
    - secure: "X+6Bedk+8kZblTukImu+1mVBCR+NS5wBCDHnz/z2+aF7R0RHbYCeA2wrM46aAFS7g79X1L7+FBUh7UB+KYCVUn8IB+jBJzuM/3AfPDVq17Fta3rEBig8boU2wqK76ziPJ/x/yIeOOEpXRSyfwqYbQJcoSXxzqTblctjZdLVZ2tKVYHEsZpzzaVxbCz9wMTRJMEw4Mju4SVStpqookpu/qVZpGHlBw76ImY/X/cfT/uXPoe8CfMjEqFZJhI8vjV5PmGvpND2UL2rY7aX5R2/XwPpwSvMz/cpZmF1Qqn50Ul9ZKSAi6PZPVmySTAu5emi75R+aGXERAQA6R2hyUSqaCJTuz2siDums5lBwYgp3WTCfhS0AJSPy5sTRX57LY+QOWLt43Z3fXVi7oCglgX0oXAknPnZM88Ub9Bl5ge5pEu7sTTmq5/w056i5GbrptbKMceN9RwOzVE0qsQFeGVpr7FkcXD+fuCxK//htwoBeHnMf5u6d2hG/zn+dqexRkjn74lPqHrjRUB8tCar/dh3Xws7mOZsdosCBM2rOZOcwvLzx+BZGGn3hykES/btbFa4MLib7L/adGNkTCVymgDwwG916AJknwuDlydf30fu64q51tWH2ViNPdYrr/LIG500Sl75RHgBtUj6+p01yQRsMU9IJLxK0O0JgOOltoRUB+E8="
